add_lunch_combo nexus_anngler-user
add_lunch_combo nexus_bullhead-user
add_lunch_combo nexus_flo-user
add_lunch_combo nexus_flounder-user
add_lunch_combo nexus_hammerhead-user
add_lunch_combo nexus_shamu-user
